# Generated by Django 4.0.6 on 2022-12-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fenix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('actividad', models.CharField(default=0, max_length=100)),
                ('urbrur', models.CharField(default=0, max_length=50)),
                ('tipo', models.CharField(default=0, max_length=50)),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('cantidad', models.CharField(default=0, max_length=50)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('fecha', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Fénix',
                'verbose_name_plural': 'Fénix',
            },
        ),
        migrations.CreateModel(
            name='NovedadBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=200)),
                ('descripcion', models.CharField(default='--', max_length=200)),
            ],
            options={
                'verbose_name': 'Novedades',
                'verbose_name_plural': 'Novedades',
            },
        ),
        migrations.CreateModel(
            name='Perseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('actividad', models.CharField(default=0, max_length=100)),
                ('instalador', models.CharField(default=0, max_length=200)),
                ('fecha', models.CharField(default=0, max_length=50)),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('cantidad', models.CharField(default=0, max_length=50)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total', models.CharField(default=0, max_length=50)),
                ('acta', models.CharField(default=0, max_length=50)),
                ('descuento_de_fenix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Perseo',
                'verbose_name_plural': 'Perseo',
            },
        ),
        migrations.CreateModel(
            name='ProducidoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('fecha', models.CharField(default=0, max_length=100)),
                ('valor_fenix', models.CharField(default=0, max_length=100)),
                ('valor_perseo_descuento', models.CharField(default=0, max_length=100)),
                ('producido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producido diario',
                'verbose_name_plural': 'Producido diario',
            },
        ),
        migrations.CreateModel(
            name='PromedioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('valor_producido_mes', models.CharField(default=0, max_length=100)),
                ('numero_de_dias_laborados', models.CharField(default=0, max_length=100)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonificacion_cuadrilla', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonificacion_persona', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Promedio',
                'verbose_name_plural': 'Promedio',
            },
        ),
    ]
