# Generated by Django 4.0.6 on 2022-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0002_alter_perseo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenix',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
