# Generated by Django 3.2 on 2022-11-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(default=0, max_length=200)),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regional',
                'db_table': 'regional',
                'managed': True,
            },
        ),
    ]
